<x-app-layout :title="$product->exists ? 'Edit Produk' : 'Tambah Produk'" module="inventory" :module-data="config('modules.inventory')">
    <div class="max-w-3xl"><a href="{{ route('products.index') }}" class="text-sm font-semibold text-brand-700">← Kembali ke daftar</a><h1 class="mt-4 text-2xl font-semibold tracking-tight">{{ $product->exists ? 'Edit Produk' : 'Tambah Produk' }}</h1>
        <form method="POST" action="{{ $product->exists ? route('products.update', $product) : route('products.store') }}" class="mt-7 grid gap-6">@csrf @if ($product->exists) @method('PUT') @endif
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Informasi Produk</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-ui.input label="SKU" name="sku" :value="$product->sku" required placeholder="FG-330ML" /><x-ui.input label="Nama Produk" name="name" :value="$product->name" required /><div class="grid gap-1.5"><label for="type" class="text-sm font-medium text-slate-700">Jenis</label><select id="type" name="type" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm">@foreach ($types as $type)<option value="{{ $type->value }}" @selected(old('type', $product->type?->value) === $type->value)>{{ $type->label() }}</option>@endforeach</select></div><div class="grid gap-1.5"><label for="unit_id" class="text-sm font-medium text-slate-700">Satuan</label><select id="unit_id" name="unit_id" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm">@foreach ($units as $unit)<option value="{{ $unit->id }}" @selected((int) old('unit_id', $product->unit_id) === $unit->id)>{{ $unit->name }} ({{ $unit->code }})</option>@endforeach</select></div></div></section>
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Stok & Harga</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-ui.input label="Stok Minimum" name="minimum_stock" type="number" min="0" step="0.001" :value="$product->minimum_stock ?? 0" required /><x-ui.input label="Stok Maksimum" name="maximum_stock" type="number" min="0" step="0.001" :value="$product->maximum_stock" /><x-ui.input label="Harga Beli" name="purchase_price" type="number" min="0" step="1" :value="$product->purchase_price ?? 0" required /><x-ui.input label="Harga Jual per Satuan" name="selling_price" type="number" min="0" step="1" :value="$product->selling_price ?? 0" required /><div class="grid gap-1.5"><label for="is_active" class="text-sm font-medium text-slate-700">Status</label><select id="is_active" name="is_active" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm"><option value="1" @selected(old('is_active', $product->is_active ?? true))>Aktif</option><option value="0" @selected(! old('is_active', $product->is_active ?? true))>Tidak aktif</option></select></div><div class="grid gap-1.5 sm:col-span-2"><label for="notes" class="text-sm font-medium text-slate-700">Catatan</label><textarea id="notes" name="notes" rows="3" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('notes', $product->notes) }}</textarea></div></div></section>
            <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('products.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold">Batal</a><x-ui.button type="submit">{{ $product->exists ? 'Simpan Perubahan' : 'Simpan Produk' }}</x-ui.button></div>
        </form>
    </div>
</x-app-layout>
