<x-app-layout :title="$supplier->exists ? 'Edit Supplier' : 'Tambah Supplier'" module="suppliers" :module-data="config('modules.suppliers')">
    <div class="max-w-3xl"><a href="{{ route('suppliers.index') }}" class="text-sm font-semibold text-brand-700">← Kembali ke daftar</a><h1 class="mt-4 text-2xl font-semibold tracking-tight">{{ $supplier->exists ? 'Edit Supplier' : 'Tambah Supplier' }}</h1>
        <form method="POST" action="{{ $supplier->exists ? route('suppliers.update', $supplier) : route('suppliers.store') }}" class="mt-7 grid gap-6">@csrf @if ($supplier->exists) @method('PUT') @endif
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Informasi Supplier</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-ui.input label="Kode Supplier" name="supplier_code" :value="$supplier->supplier_code" required placeholder="SUP-001" /><x-ui.input label="Nama Supplier" name="name" :value="$supplier->name" required /><x-ui.input label="Telepon" name="phone" :value="$supplier->phone" /><x-ui.input label="Email" name="email" type="email" :value="$supplier->email" /><div class="grid gap-1.5 sm:col-span-2"><label for="address" class="text-sm font-medium text-slate-700">Alamat</label><textarea id="address" name="address" rows="3" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('address', $supplier->address) }}</textarea></div></div></section>
            <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="font-semibold">Ketentuan Pembayaran</h2><div class="mt-5 grid gap-5 sm:grid-cols-2"><x-ui.input label="Termin Pembayaran (hari)" name="payment_term" type="number" min="0" max="365" :value="$supplier->payment_term ?? 0" required /><div class="grid gap-1.5"><label for="status" class="text-sm font-medium text-slate-700">Status</label><select id="status" name="status" class="min-h-11 rounded-lg border border-slate-300 px-3 text-sm"><option value="active" @selected(old('status', $supplier->status ?? 'active') === 'active')>Aktif</option><option value="inactive" @selected(old('status', $supplier->status) === 'inactive')>Tidak aktif</option></select></div><div class="grid gap-1.5 sm:col-span-2"><label for="notes" class="text-sm font-medium text-slate-700">Catatan</label><textarea id="notes" name="notes" rows="3" class="rounded-lg border border-slate-300 px-3 py-2 text-sm">{{ old('notes', $supplier->notes) }}</textarea></div></div></section>
            <div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><a href="{{ route('suppliers.index') }}" class="inline-flex min-h-11 items-center justify-center rounded-lg border border-slate-300 bg-white px-4 text-sm font-semibold">Batal</a><x-ui.button type="submit">{{ $supplier->exists ? 'Simpan Perubahan' : 'Simpan Supplier' }}</x-ui.button></div>
        </form>
    </div>
</x-app-layout>
